### ISSUE TITLE
driver for  NXP i.MX7D board 

### ISSUE THREAD

**Issue by 1abid** [Polidea/Polithings#12]
Hello , Nice to have this driver library you wrote . I am new to IoT and I got the development preview 6 of NXP i.MX7D from google developer days India . I am using a ULN2003A stepper motor with my board . I read your driver's readme file and it says it works only with Raspberry PI 3 . But reading through code I didn't find anything specific to RP 3 . 

Would You please help me to do some tweak if needed for this driver so I can use this with my NXP i.MX7D

**Comment by MarcinKornacki** [comment]
Hello Abid,
We've tested our library only on RPi 3, so we can't guarantee it works on other boards as well. Examples works by default on RPi 3 because of its specific pinouts. If there were no significant changes since developer preview 4 in Android Things, I assume you should be able to run our library on NXP i.MX7D. Try our example from "ULN2003StepperMotorActivity" changing GPIO pins to suitable for NXP i.MX7D before.

In your case the changes should look like this:

`val in1Pin = "GPIO2_IO01"
val in2Pin = "GPIO2_IO02"
val in3Pin = "GPIO2_IO00"
val in4Pin = "GPIO2_IO05"`

Let us know if you manage to run your motor. If you have any additional questions, feel free to ask.

**Comment by 1abid** [comment]
Thanks a lot for the support mate . I have connected my NXP i.MX7D with my ULN2003A and it is working perfectly .

**Comment by 1abid** [comment]
Thans a lot Marcin Kornacki , 
I have tried this for my NXP i.MX7D . but got this error . 
<img width="1829" alt="screen shot 2017-12-13 at 2 25 00 pm" src="https://user-images.githubusercontent.com/6067801/33928919-c566d41a-e011-11e7-9e0c-5c0355399a8b.png">
<img width="1501" alt="screen shot 2017-12-13 at 2 25 37 pm" src="https://user-images.githubusercontent.com/6067801/33928920-c802d084-e011-11e7-9dc8-22db6d025bb1.png">

I didn't find out where is the root of the problem . Please help me

**Comment by 1abid** [comment]
Hello , I have solved the previous problem . there was a line missing in my manifest.xml 
`<uses-library android:name="com.google.android.things"/>`

but after this I got this error for rotating the motor

**This is my code**
`val stepper = ULN2003StepperMotor(in1GpioId = in1Pin,
                in2GpioId = in2Pin,
                in3GpioId = in3Pin,
                in4GpioId = in4Pin)

        //Perform a rotation and add rotation listener

        stepper.rotate(degrees = 180.0,
                direction = Direction.CLOCKWISE,
                resolutionId = ULN2003Resolution.HALF.id,
                rpm = 2.5,
                rotationListener = object : RotationListener {
                    override fun onStarted() {
                        Log.i(TAG, "rotation started")
                    }

                    override fun onFinishedSuccessfully() {
                        Log.i(TAG, "rotation finished")
                    }

                    override fun onFinishedWithError(degreesToRotate: Double, rotatedDegrees: Double, exception: Exception) {

                        exception.printStackTrace()
                        Log.e(TAG, "error, degrees to rotate: {$degreesToRotate}  rotated degrees: {$rotatedDegrees}")
                    }
                })
        

        // Close the ULN2003StepperMotor when all moves are finished. Otherwise close() will terminate current and pending rotations.
        stepper.close()`

this is the exception I got 

<img width="1405" alt="screen shot 2017-12-13 at 3 32 16 pm" src="https://user-images.githubusercontent.com/6067801/33931828-6ff2e708-e01b-11e7-8415-54ee079be1e3.png">

**Comment by MarcinKornacki** [comment]
Hello Abid,

"rotate" method is not blocking. It runs the code on a separate thread. You call "close" right after "rotate", so you interrupt the rotation process. You should call "stepper.close()" inside onFinishedSuccessfully() or onPause()

**Comment by 1abid** [comment]
MarcinKornacki  , Thanks a lot now I didn't get that exception . but I have faced another issue .
this code run perfectly and log show "rotation started and it gets the callback rotation successful "
what strange is I have checked the connection and everything but motor is not rotating .

**Comment by MarcinKornacki** [comment]
Abid, do you have ULN2003 with four LEDs mounted on a board? If so, they should blink while running the code. Do they blink?

**Comment by 1abid** [comment]
MarcinKornacki , unfortunately none of them blink . I have almost zero Idea , so I could't debug the board with multimeter . I thought the motor is broken or something but this motor works perfectly [a php code running in Raspberry pi 3](https://github.com/nhevan/TheNovelist/blob/master/app/PrimaryHandController.php) 

So I thought before implementing this code I need to study a deeper . I read through the article you added on the readme file . my insctint is saying here is the root of the problem . 

my gpios are 
val in1Pin = "GPIO2_IO01" //blue
val in2Pin = "GPIO2_IO02" //pink
val in3Pin = "GPIO2_IO00" //yellow 
val in4Pin = "GPIO2_IO05"  //orange 

so if I use this method from your library 
![screen shot 2017-12-19 at 4 23 10 pm](https://user-images.githubusercontent.com/6067801/34152489-f3ad2754-e4d8-11e7-951b-86975d98dd01.png)
it doesn't matches with the article . as my GPIOs are varies from yours 
![screen shot 2017-12-19 at 4 19 15 pm](https://user-images.githubusercontent.com/6067801/34152536-1c9f83f0-e4d9-11e7-805f-83c0f5342bbf.png)

please help me . without this driver I can't move forward

**Comment by MarcinKornacki** [comment]
Abid, did you try running the code on Android Things installed on Raspberry Pi 3?
Even if GPIOs order does not match, you should see them blinking. 
I suspect that GPIOs are not opened correctly.

Can you run this code to see list of available GPIOs? I don’t have NXP i.MX7D, so i can’t test it on my own.
`PeripheralManagerService manager = new PeripheralManagerService();
List<String> portList = manager.getGpioList();
if (portList.isEmpty()) {
    Log.i(TAG, "No GPIO port available on this device.");
} else {
    Log.i(TAG, "List of available ports: " + portList);
}`

What is more, you can initialize your GPIOs and set one sequence statically to see if there is a signal on a pin. You can check them by using e.g. multimeter. A code should look something like this:

`class TestActivity : AppCompatActivity() {

    val in1Pin = "BCM4"
    val in2Pin = "BCM17"
    val in3Pin = "BCM27"
    val in4Pin = "BCM22"

    lateinit var in1Gpio : Gpio
    lateinit var in2Gpio : Gpio
    lateinit var in3Gpio : Gpio
    lateinit var in4Gpio : Gpio


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)


        val in1Gpio = initGpio(in1Pin)
        val in2Gpio = initGpio(in2Pin)
        val in3Gpio = initGpio(in3Pin)
        val in4Gpio = initGpio(in4Pin)


        in1Gpio.value = true
        in2Gpio.value = false
        in3Gpio.value = false
        in4Gpio.value = false
    }

    private fun initGpio(name : String) : Gpio{
        val gpio = PeripheralManagerService().openGpio(name)
        gpio.setDirection(Gpio.DIRECTION_OUT_INITIALLY_LOW)
        gpio.setActiveType(Gpio.ACTIVE_HIGH)
        return gpio
    }

    override fun onDestroy() {
        super.onDestroy()

        in1Gpio.close()
        in2Gpio.close()
        in3Gpio.close()
        in4Gpio.close()
    }
}`

**Comment by hirosz** [comment]
I have NXP i.MX7D and it's work fine but driver is not up to date. You have to change open functions to:
` open fun openGpio(name: String)
            =  PeripheralManager.getInstance().openGpio(name)`
